version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports: ["2181:2181"]
  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    ports: ["9092:9092"]
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: >-
        word-count-input-topic:3:1,
        word-count-output-topic:3:1,
        twitter-input-topic:3:1